comid.psa-cert-triples = 4

$$triples-map-extension //= (
  comid.psa-cert-triples => [ + psa-cert-triple-record ]
)

psa.immutable-rot = 1
psa.mutable-rot = 2

psa-rot-descriptor = {
  psa.immutable-rot => psa-implementation-id-type
  psa.mutable-rot => [ * psa-swcomp-id ]
}

psa-cert-triple-record = [
  psa-rot-descriptor
  psa-cert-num-type
]

psa-cert-num-type = text .regexp "[0-9]{13} - [0-9]{5}"
