comid.psa-fw-patch-triples = 5

$$triples-map-extension //= (
  comid.psa-fw-patch-triples => one-or-more<psa-fw-patch-triple-record>
)

security-critical = bool

psa-fw-patch-triple-record = [
  measurement-map,  / "old" firmware component /
  measurement-map,  / "new" firmware component /
  security-critical / true if "new" fixes a security vulnerability of "old" /
]
