psa-swcomp-id = {
  psa.measurement-type => text
  psa.version => text
  psa.signer-id => psa.hash-type
}

psa.hash-type = bytes .size 32 / bytes .size 48 / bytes .size 64

psa.measurement-type = 1
psa.version = 4
psa.signer-id = 5
