comid.psa-swrel-triples = 5

$$triples-map-extension //= (
  comid.psa-swrel-triples => [ + psa-swrel-triple-record ]
)

psa.updates = 1
psa.patches = 2

psa-swrel-type-choice /= psa.updates
psa-swrel-type-choice /= psa.patches

psa-security-critical = bool

psa-swrel-rel = [
  psa-swrel-type-choice ; one of "patches" or "updates"
  psa-security-critical ; true if it fixes a security critical bug
}

psa-swrel-triple-record = [
  environment-map
  [ ; the anonymous, reified SW relation triple
    psa-swcomp-id ; identifier of the "new" firmware
    psa-swrel-rel ; patches, updates and the security flag
    psa-swcomp-id ; identifier of the "old" firmware
  ]
]
