comid.psa-swrel-triples = 5

$$triples-map-extension //= (
  comid.psa-swrel-triples => [ + psa-swrel-triple-record ]
)

psa-security-critical = bool

psa.update = 1
psa.patch  = 2

$psa-swrel-type /= psa.updates
$psa-swrel-type /= psa.patches

psa-swrel-triple-record = [
  environment-map
  [ ; the implicit, reified triple
    psa-swcomp-id         ; identifier of the "new" firmware
    $psa-swrel-type       ; one of "patches" or "updates"
    psa-security-critical ; true if it fixes a security critical bug
    psa-swcomp-id-map     ; identifier of the "old" firmware
  ]
]
