name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: thomasfossati/kdrfc:latest
    steps:
    - uses: actions/checkout@v2
    - name: build draft
      run: make && mkdir -p public/${GITHUB_REF##*/} && cp draft-xyz-rats-psa-endorsements.html public/${GITHUB_REF##*/}
    - name: Archive draft
      uses: actions/upload-artifact@v2
      with:
        name: draft-latest
        path: draft-xyz-rats-psa-endorsements.html
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
