name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: thomasfossati/kdrfc:latest
    steps:
    - uses: actions/checkout@v2
    - name: build draft
      run: make
    - name: Archive draft
      uses: actions/upload-artifact@v2
      with:
        name: draft-latest
        path: draft-xyz-rats-psa-endorsements.html
